name: point2mesh
channels:
  - pytorch
  - defaults
  - conda-forge
  - fvcore
  - pytorch3d
dependencies:
  - python=3.8.2
  - numpy
  - pytorch
  - torchvision
  - fvcore
  - pytorch3d
  - pip
  - pip:
    - pytest
